version: 0.2

env:
  variables:
    ECR_REPO: "339712871948.dkr.ecr.us-east-1.amazonaws.com/order"
    ECR_REGION: "us-east-1"
    CONTAINER_NAME: "lks-order-container"

phases:
  install:
    runtime-versions:
      nodejs: 16
      docker: 20
    commands:
      - yum update -y
      - yum install -y curl unzip aws-cli
      - aws --version
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Running unit tests..."
      - npm run test
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO:latest .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${ECR_REPO}:latest > imagedefinitions.json
      - echo "Build complete."

reports:
  test-report:
    files:
      - 'report/test-result.xml'
    file-format: JUNITXML

artifacts:
  files:
    - imagedefinitions.json
