version: 0.2

env:
  variables:
    ECR_REPO: "339712871948.dkr.ecr.us-east-1.amazonaws.com"
    ECR_REGION: "us-east-1"
    CONTAINER_NAME: "lks-order-container"
    AWS_REGION: "us-east-1"
    AWS_DYNAMODB_TABLE_PROD: "lks-order-production"
    AWS_DYNAMODB_TABLE_TEST: "lks-order-testing"

phases:
  install:
    runtime-versions:
      nodejs: 18
      docker: 20
    commands:
      - echo "Checking OS details..."
      - cat /etc/os-release || echo "OS info not found"
      - command -v apk || echo "APK not found!"
      - echo "Installing dependencies..."
      - apk add --no-cache docker-cli
      - npm install
      - echo "Check npm"
      - npm list mocha
      - npm list mocha-junit-reporter
      - echo "Installing AWS Elastic Beanstalk CLI..."
      - python3 -m venv ebcli-venv
      - source ebcli-venv/bin/activate
      - pip install --upgrade pip
      - pip install awsebcli

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ECR_REPO

  build:
    commands:
      - echo "Running unit tests..."
      - npm run test
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO}/order:latest .

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push ${ECR_REPO}/order:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${ECR_REPO}/order:latest > imagedefinitions.json
      - echo "Build complete."

reports:
  test-report:
    files:
      - 'report/test-result.xml'
    file-format: JUNITXML

artifacts:
  files:
    - imagedefinitions.json
